# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wingman',
                'doc_host': 'https://lukexyz.github.io',
                'git_url': 'https://github.com/lukexyz/wingman',
                'lib_path': 'wingman'},
  'syms': {'wingman.core': {'wingman.core.foo': ('core.html#foo', 'wingman/core.py')}}}
